name: nuc-606
author: nuc-606 vision group
url: https://nuc-606.github.io/
baseurl: 
resume_site: https://nuc-606.github.io/
description: the blog for nuc-606 vision group
github_username: nuc-606
github: https://github.com/nuc-606
plugins: [jekyll-paginate]
permalink: /:year-:month-:day-:title
paginate: 12
paginate_path: "/page/:num/"
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
highlighter: rouge
markdown: kramdown
comments :
  gitalk :
    clientID : 27eb2023a71e3444d051
    clientSecret : b9a349159ec139b4b788a921aa783a1d181ad016
    repo : nuc-606.github.io
    owner : nuc-606
    admin : nuc-606
