name: nuc-606
author: nuc-606 vision group
url: https://nuc-606.github.io/
baseurl: 
resume_site: https://nuc-606.github.io/
description: the blog for nuc-606 vision group
github_username: nuc-606
github: https://github.com/nuc-606
plugins: [jekyll-paginate]
permalink: /:year-:month-:day-:title
paginate: 12
paginate_path: "/page/:num/"
exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']
highlighter: rouge
markdown: kramdown
comments :
  gitalk :
    clientID : 94222c876cdb241854e6
    clientSecret : 5bf05db8cf19cc6496c5e22e3d57f53c99f3fcd5
    repo : nuc-606.github.io
    owner : nuc-606
    admin : nuc-606
